import { Header } from "@/components/ui/header/Header";
import { Footer } from "@/components/ui/footer/Footer";

export const metadata = {
  title: "Next.js Week 3 Classwork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}